//
//  QuestionareInteractor.swift
//  KongBank
//
//  Created by Sorawit Trutsat on 1/4/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QuestionareBusinessLogic {
    func getLoanCondition(request: Questionare.Loan.Request)
}

protocol QuestionareDataStore {
    //var name: String { get set }
}

class QuestionareInteractor: QuestionareBusinessLogic, QuestionareDataStore {
    var presenter: QuestionarePresentationLogic?
    var worker: QuestionareWorker?
    
    func getLoanCondition(request: Questionare.Loan.Request) {
        let career = request.carrer
        var rate = 0.0
        var period = 0
        var load = 0
        
        switch career {
        case .governmentEmployee:
            rate = 0.5
            period = 60
            load = 2000000
        case .companyEmployee:
            rate = 1.5
            period = 36
            load = 1500000
        case .ownBusiness:
            rate = 2.5
            period = 24
            load = 100000
        }
        
        let response = Questionare.Loan.Response(carrer: career, rate: rate, period: period, loan: load)
        presenter?.presentLoanInformation(response: response)
    }
}
