//
//  QuestionarePresenter.swift
//  KongBank
//
//  Created by Sorawit Trutsat on 1/4/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QuestionarePresentationLogic {
    func presentLoanInformation(response: Questionare.Loan.Response)
}

class QuestionarePresenter: QuestionarePresentationLogic {
    weak var viewController: QuestionareDisplayLogic?
    
    func presentLoanInformation(response: Questionare.Loan.Response) {
        let message = "คุณสามารถกู้ด้วยวงเงินสูงสุด \(response.loan) บาท อัตราดอกเบี้ย \(response.rate)% ระยะเวลาผ่อนชำระสูงสุด \(response.period) งวด"
        let isGovernmentEmployeeOpen = response.carrer == .governmentEmployee
        let isCompanyEmployeeOpen = response.carrer == .companyEmployee
        let isOwnBusinessEmployeeOpen = response.carrer == .ownBusiness
        
        let viewModel = Questionare.Loan.ViewModel(message: message,
                                                   isGovernmentEmployeeOpen: isGovernmentEmployeeOpen,
                                                   isCompanyEmployeeOpen: isCompanyEmployeeOpen,
                                                   isOwnBussinessEmployeeOpen: isOwnBusinessEmployeeOpen)
        viewController?.displayLoanCondition(viewModel: viewModel)
    }
}
