//
//  QuestionareModels.swift
//  KongBank
//
//  Created by Sorawit Trutsat on 1/4/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Questionare {
    enum Career {
        case governmentEmployee
        case companyEmployee
        case ownBusiness
    }

    enum Loan {
        struct Request {
            var carrer: Career
        }
        
        struct Response {
            var carrer: Career
            var rate: Double
            var period: Int
            var loan: Int
        }
        
        struct ViewModel {
            var message: String
            var isGovernmentEmployeeOpen: Bool
            var isCompanyEmployeeOpen: Bool
            var isOwnBussinessEmployeeOpen: Bool
            
        }
    }
}

